services:
  database:
    image: postgres:latest
    container_name: ${DATABASE_HOST}
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_HOST: ${DATABASE_HOST}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - postgres-storage:/var/lib/postgresql/data
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    restart: on-failure
    networks:
      - app-network
    healthcheck:
      test: sh -c "pg_isready -U ${DATABASE_USER} -d ${DATABASE_NAME} -h ${DATABASE_HOST} -p ${DATABASE_PORT}"
      start_period: 3s
      interval: 3s
      timeout: 1s
      retries: 5

  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: ${RABBITMQ_HOST}
    ports:
      - ${RABBITMQ_AMQP_PORT}:${RABBITMQ_AMQP_PORT}
      - ${RABBITMQ_MANAGEMENT_PORT}:${RABBITMQ_MANAGEMENT_PORT}
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  migration:
    container_name: ${MIGRATION_HOST}
    build: ./apps/migration_service
    volumes:
      - ./apps/migration_service/migrations:/app/migrations
      - ./apps/models:/app/models
    env_file: .env
    depends_on:
      database:
        condition: service_healthy
    restart: on-failure
    networks:
      - app-network

  auth:
    container_name: ${AUTH_HOST}
    build: ./apps/auth_service
    volumes:
      - ./apps/models:/app/models
      - ./apps/schemas:/app/schemas
      - ./apps/infrastructure:/app/infrastructure
    env_file: .env
    ports:
      - ${AUTH_PORT}:${AUTH_PORT}
    depends_on:
      database:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      migration:
        condition: service_completed_successfully
    restart: on-failure
    networks:
      - app-network


networks:
  app-network:
    driver: bridge

volumes:
  postgres-storage:
  rabbitmq_data:
